import type { TextStyleModel } from "../types";

export const SAMPLE_TEXT_STYLES: TextStyleModel[] = [
  {
    type: "TEXT",
    name: "Headings/H1",
    description: "Primary page title",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "Bold" },
    fontSize: 36,
    letterSpacing: { unit: "PERCENT", value: -2 },
    lineHeight: { unit: "PERCENT", value: 120 },
    paragraphIndent: 0,
    paragraphSpacing: 20,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Headings/H2",
    description: "Section heading",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "Bold" },
    fontSize: 28,
    letterSpacing: { unit: "PERCENT", value: -1 },
    lineHeight: { unit: "PERCENT", value: 125 },
    paragraphIndent: 0,
    paragraphSpacing: 16,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Headings/H3",
    description: "Subsection heading",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "SemiBold" },
    fontSize: 22,
    letterSpacing: { unit: "PERCENT", value: 0 },
    lineHeight: { unit: "PERCENT", value: 130 },
    paragraphIndent: 0,
    paragraphSpacing: 12,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Headings/H4",
    description: "Card or group heading",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "SemiBold" },
    fontSize: 18,
    letterSpacing: { unit: "PERCENT", value: 0 },
    lineHeight: { unit: "PERCENT", value: 135 },
    paragraphIndent: 0,
    paragraphSpacing: 8,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Headings/H5",
    description: "Small heading or label",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "Medium" },
    fontSize: 16,
    letterSpacing: { unit: "PERCENT", value: 0 },
    lineHeight: { unit: "PERCENT", value: 140 },
    paragraphIndent: 0,
    paragraphSpacing: 6,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Headings/H6",
    description: "Overline or smallest heading",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "Medium" },
    fontSize: 14,
    letterSpacing: { unit: "PERCENT", value: 2 },
    lineHeight: { unit: "PERCENT", value: 140 },
    paragraphIndent: 0,
    paragraphSpacing: 4,
    listSpacing: 0,
    textCase: "UPPER",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
  {
    type: "TEXT",
    name: "Body/Body",
    description: "Default body text",
    descriptionMarkdown: "",
    documentationLinks: [],
    fontName: { family: "Inter", style: "Regular" },
    fontSize: 16,
    letterSpacing: { unit: "PERCENT", value: 0 },
    lineHeight: { unit: "PERCENT", value: 150 },
    paragraphIndent: 0,
    paragraphSpacing: 12,
    listSpacing: 0,
    textCase: "ORIGINAL",
    textDecoration: "NONE",
    leadingTrim: "NONE",
    hangingPunctuation: false,
    hangingList: false,
  },
];
